# See the dedicated "version" documentation section.
version: "2"
linters:
  enable:
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2 
formatters:
  # See the dedicated "formatters" documentation section.
  enable:
    - gofmt
issues:
  # See the dedicated "issues" documentation section.
  fix: true
# Output configuration options.
# output:
  # See the dedicated "output" documentation section.
  # option: value
# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  timeout: 5m
severity:
  # See the dedicated "severity" documentation section.
  default: ""